kind: Service
apiVersion: v1
metadata:
  name: ${itemAppName}
  labels:
    app: ${itemAppName}
spec:
  ports:
    - name: http
      protocol: TCP
      port: ${itemAppPort}
      targetPort: ${itemAppPort}
  selector:
    app: ${itemAppName}
  type: ClusterIP